### ISSUE TITLE
Stop containers instead of kill

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/cf-containers-broker#55]
in actions `#destroy` and `#update` we are [killing](https://github.com/cloudfoundry-community/cf-containers-broker/blob/master/app/models/docker_manager.rb#L111) the containers. Are there objections to `stop` them instead? That way we would have a chance to trap the SIGTERM signal and run a shutdown script in the container.

@frodenas do you remeber why this was originally coded as kill?

cc @drnic

**Comment by frodenas** [comment]
I believe I had some problems when I tried to just stop the container instead of killing it. It has been a long time since I implemented this, but IIRC there were two issues: 
* At that time (Docker didn't even reach v1) sending a `stop` signal didn't work will all containers, they didn't stop and became somewhat of zombie's processes.
* `stop` had a 30 secs timeout, this was not enough time to deal with the service broker's 60 sec timeout, so the CC request was killed (and returned an error to the user) but the container was deleted.

Again, this happened a long time ago. Maybe now this has been fixed, and sending a `stop` signal will work seamlessly.

**Comment by bodymindarts** [comment]
Currently `stop` has a default timeout of 10 seconds and after that SIGKILL is sent. From tests using `stop` in our systems I have not seen any issues.
I assume the issues you encountered are no longer an issue and it is safe to merge.
